"""The exported board data is served to the public internet.

What matters here is not that the export works, but that it stays a *subset*:
raw model replies, token counts per row and attempt metadata must never end up
in a file anyone can fetch.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from export_web_data import TRIAGE_FIELDS, build_payload  # noqa: E402


def _document(**overrides):
    record = {
        "id": "REQ-001",
        "channel": "Slack",
        "timestamp": "2026-06-08T09:14:00",
        "raw_text": "текст запиту",
        "status": "ok",
        "triage": {
            "category": "звіт/аналітика",
            "target_department": None,
            "domain": "маркетинг",
            "priority": "medium",
            "short_summary": "суть",
            "requested_actions": ["дія"],
            "needs_clarification": False,
            "confidence": 0.9,
            "clarifying_questions": [],
            "mentioned_systems": ["Google Ads"],
            "is_actionable": True,
        },
        "error": None,
        "meta": {
            "attempts": 2,
            "model": "gemini-3.1-flash-lite",
            "prompt_tokens": 2185,
            "output_tokens": 190,
            "applied_rules": [],
        },
    }
    record.update(overrides)
    return {
        "generated_at": "2026-09-02T18:30:48+00:00",
        "model": "gemini-3.1-flash-lite",
        "stats": {"total": 1, "ok": 1, "failed": 0, "llm_calls": 1},
        "requests": [record],
    }


def test_export_keeps_only_the_fields_the_page_renders():
    payload = build_payload(_document())
    assert list(payload["requests"][0]["triage"]) == list(TRIAGE_FIELDS)


def test_per_row_metadata_never_reaches_the_browser():
    payload = build_payload(_document())
    exported = payload["requests"][0]
    assert "meta" not in exported
    assert "error" not in exported
    assert "status" not in exported
    # Nothing anywhere in the row should carry the model's raw reply.
    assert "last_raw_response" not in json.dumps(payload, ensure_ascii=False)


def test_failed_rows_are_not_placed_on_the_board():
    document = _document(status="failed", triage=None)
    assert build_payload(document)["requests"] == []


def test_run_provenance_is_carried_through():
    payload = build_payload(_document())
    assert payload["model"] == "gemini-3.1-flash-lite"
    assert payload["source_run"]["ok"] == 1
    assert payload["source_run"]["total"] == 1


def test_exported_file_on_disk_matches_the_contract():
    """The committed asset is what actually ships — check it, not just the code."""
    path = Path(__file__).resolve().parents[1] / "web" / "public" / "data" / "baseline.json"
    if not path.exists():
        return  # generated by scripts/export_web_data.py; absent in a fresh clone
    data = json.loads(path.read_text(encoding="utf-8"))
    assert data["requests"], "exported board is empty"
    for row in data["requests"]:
        assert set(row) == {"id", "channel", "timestamp", "raw_text", "triage"}
        assert list(row["triage"]) == list(TRIAGE_FIELDS)
